import type { RunState, SaveData } from '../balance';
import { FLOORS } from '../data/floors';
import { SPECIAL_VAULTS } from '../data/specialVaults';
import { FloorManager } from '../systems/FloorManager';
import { ChestTierManager } from '../systems/ChestTierManager';
import { summary } from '../systems/RunManager';
import { TIER_IDS } from '../types/chest';
import { icon, vaultArt } from './art';
const money=(n:number)=>n.toLocaleString('ko-KR');
export function floorHud(run:RunState){const f=FloorManager.definition(run);return `<div class="floor-hud"><div><strong>B${run.currentFloor}</strong><span>${f.englishName}<small>${f.name} · Round ${run.currentFloorRound} / ${f.roundCount} · 보상 ×${f.rewardMultiplier}</small></span></div><ol aria-label="금고 층 진행도">${FLOORS.map((f,i)=>`<li class="${i+1===run.currentFloor?'current':i+1<run.currentFloor?'complete':''}" ${i+1===run.currentFloor?'aria-current="step"':''} title="${f.name}"><span>B${i+1}</span><b>${i+1===run.currentFloor?'◉':i+1<run.currentFloor?'●':'○'}</b></li>`).join('')}</ol></div>`;}
export function roomHeading(run:RunState){const room=SPECIAL_VAULTS.find(v=>v.id===run.activeSpecial);return room?`<div class="special-banner"><span>SPECIAL VAULT</span><h3>${room.englishName}</h3><p>${room.description}</p></div>`:'';}
export function decisionHtml(run:RunState){
 const f=FloorManager.definition(run),room=SPECIAL_VAULTS.find(v=>v.id===run.activeSpecial);
 if(run.phase==='special-offer')return `<section class="vault-decision"><p class="eyebrow">SPECIAL VAULT DISCOVERED</p><div class="decision-art">${vaultArt()}</div><h2>${room!.englishName}</h2><p>${room!.name}</p><p class="decision-description">${room!.description}</p><div class="post-choice"><button class="primary" data-action="special-enter">${room!.name}에 들어간다 ${icon('arrow')}</button><button class="secondary" data-action="special-skip">지나간다</button><button class="escape-btn" data-action="escape">${money(run.gold)} G 들고 탈출</button></div></section>`;
 if(run.phase==='special'&&run.activeSpecial==='shop')return `${roomHeading(run)}<div class="shop-grid">${run.shopOffers.map(o=>`<article class="shop-item"><span>${icon(o.id==='insurance'?'shield':'eye')}</span><h3>${o.name}</h3><p>${o.description}</p><strong>${money(o.cost)} G</strong><button class="primary" data-action="shop-buy" data-id="${o.id}" ${o.purchased||run.gold<o.cost?'disabled':''}>${o.purchased?'보유 중':run.gold<o.cost?'골드 부족':'구매한다'}</button></article>`).join('')}</div><div class="post-choice"><button class="secondary" data-action="special-leave">거래를 마치고 진행</button><button class="escape-btn" data-action="escape">${money(run.gold)} G 들고 탈출</button></div>`;
 const deepest=run.currentFloor===FLOORS.length,next=FLOORS[run.currentFloor];
 return `${run.revealed?`<div class="floor-reveal" aria-label="층의 마지막 상자 결과">${run.chests.map((c,i)=>`<span class="${i===run.selected?'chosen':''}"><small>${c.tier.toUpperCase()} · ${i===run.selected?'선택':'NEAR MISS'}</small><b>${c.result.name??c.result.type.toUpperCase()}</b>${i===run.selected&&c.payout?`<em>${c.payout>0?'+':''}${money(c.payout)} G</em>`:''}</span>`).join('')}</div>`:''}<section class="vault-decision ${deepest?'deepest-decision':''}"><p class="eyebrow">${deepest?'THE DEEPEST VAULT':`B${run.currentFloor} · FLOOR CLEARED`}</p><div class="decision-art">${vaultArt()}</div><h2>${deepest?'더 이상 아래는 없다.':`${f.name}의 봉인이 풀렸다.`}</h2><p class="decision-description">${deepest?'악마가 단 하나의 상자를 남겼다. 살아서 나갈 것인가, 마지막 봉인을 풀 것인가?':`다음은 B${run.currentFloor+1} · ${next.name}. 보상 ×${next.rewardMultiplier}, 기본 위험 +${next.riskModifier}%p. 더 큰 보물이 기다립니다.`}</p><strong class="decision-gold">${money(run.gold)} <small>G · 현재 보상</small></strong><div class="post-choice"><button class="escape-btn" data-action="escape">금고를 떠난다</button><button class="primary" data-action="${deepest?'final-open':'descend'}">${deepest?'악마의 마지막 상자를 연다':'더 깊이 내려간다'} ${icon('arrow')}</button></div>${deepest?'<p class="final-risk">마지막 봉인 · RUIN 25% · JACKPOT 30% · ×10 25% · 신화 보물 20%</p>':''}</section>`;
}
export function summaryHtml(run:RunState){const s=summary(run);return `<div class="depth-summary"><div><small>DEEPEST FLOOR</small><b>B${s.deepest}</b></div><div><small>SPECIAL VAULTS</small><b>${s.specials}</b></div><div><small>HIGHEST CHEST</small><b>${s.highest?.toUpperCase()??'—'}</b></div><div><small>MYTHIC CHESTS</small><b>${s.mythic}</b></div></div><div class="tier-summary">${TIER_IDS.map(t=>`<span style="--tier-color:${ChestTierManager.definition(t).color}">${t.toUpperCase()} <b>${s.tiers[t]}</b></span>`).join('')}</div>`;}
export function depthRecords(save:SaveData){const s=save.statistics;return `<h2 class="section-heading">심층 탐험 기록</h2><div class="depth-summary"><div><small>최고 도달 층</small><b>${s.deepestFloorReached?'B'+s.deepestFloorReached:'—'}</b></div><div><small>발견한 특수방</small><b>${s.specialVaultsDiscovered}</b></div><div><small>특수방 종류</small><b>${s.specialVaultTypes.length} / 5</b></div><div><small>최고 상자 등급</small><b>${ChestTierManager.highest(s.chestTierStats)?.toUpperCase()??'—'}</b></div></div><div class="tier-summary">${TIER_IDS.map(t=>`<span style="--tier-color:${ChestTierManager.definition(t).color}">${t.toUpperCase()} <b>${s.chestTierStats[t]}</b></span>`).join('')}</div>`;}
