import Phaser from 'phaser';
import './style.css';
import { BALANCE, CHARACTERS, RELICS, createChests, rewardValue, riskForRound, type Chest, type RunState, type Settings } from './game/balance';
import { SaveManager } from './game/save';

class Atmosphere extends Phaser.Scene {
  private dust!: Phaser.GameObjects.Particles.ParticleEmitter;
  private backdrop?: Phaser.GameObjects.Graphics;
  constructor(){super('atmosphere');}
  create(){
    const {width,height}=this.scale;
    const g=this.add.graphics();
    g.fillGradientStyle(0x1b100e,0x100c0b,0x090807,0x090807,1); g.fillRect(0,0,width,height);
    for(let i=0;i<8;i++){this.add.circle(width*.12+i*width*.11,height*.23+Math.sin(i)*40,2+i%3,0xffb253,.16).setBlendMode(Phaser.BlendModes.ADD);}
    const pixel=this.add.graphics();pixel.fillStyle(0xffffff);pixel.fillRect(0,0,4,4);pixel.generateTexture('pixel',4,4);pixel.destroy();
    this.dust=this.add.particles(0,0,'pixel',{color:[0xffb253,0xb33d24,0x73422d],alpha:{start:.36,end:0},scale:{start:2,end:.3},speed:{min:3,max:16},angle:{min:250,max:290},lifespan:7000,frequency:260,quantity:1,blendMode:Phaser.BlendModes.ADD});
    this.dust.setDepth(1); this.scale.on('resize',()=>this.draw()); this.draw();
  }
  draw(){ const g=this.backdrop??(this.backdrop=this.add.graphics());g.clear();g.fillStyle(0x4b2117,.34);g.fillEllipse(this.scale.width/2,this.scale.height*.48,Math.min(900,this.scale.width*.9),Math.min(560,this.scale.height*.7));g.lineStyle(1,0xb47a39,.18);g.strokeEllipse(this.scale.width/2,this.scale.height*.48,Math.min(900,this.scale.width*.9),Math.min(560,this.scale.height*.7));g.setDepth(0); }
  update(_t:number,_dt:number){this.dust?.forEachAlive(p=>{p.y-=.04;},this);}
}
const game=new Phaser.Game({type:Phaser.CANVAS,parent:'ambient',backgroundColor:'#100c0b',transparent:false,scale:{mode:Phaser.Scale.RESIZE,width:window.innerWidth,height:window.innerHeight},scene:[Atmosphere],render:{antialias:true,roundPixels:true},fps:{target:30,forceSetTimeOut:true}});
void game;

const app=document.querySelector<HTMLElement>('#app')!;
let save=SaveManager.load();
document.documentElement.classList.toggle('reduce-motion',save.settings.reducedMotion);
let run:RunState|null=null;
let currentView:'menu'|'game'|'result'|'upgrades'|'records'|'settings'='menu';
let resultKind:'escape'|'ruin'='escape';
let tutorialStep=0;
const achievements=[['first_escape','첫 탈출','첫 탈출 성공'],['high_roller','고위험 투자자','5연승 달성'],['coward','신중한 생존자','첫 라운드 탈출'],['millionaire','백만장자','누적 1,000,000G'],['deal','악마와의 거래','Double or Nothing 성공'],['not_today','오늘은 안 돼','RUIN을 보험으로 방어']];
const money=(n:number)=>Math.floor(n).toLocaleString('ko-KR');
const multiplier=()=>run?BALANCE.multipliers[Math.min(run.streak,BALANCE.multipliers.length-1)]!*(1+(save.upgrades.greed??0)*.04)*(run.relics.includes('ring')?1.3:1)*(run.fever?1.25:1):1;
const persist=()=>SaveManager.save(save);
function addAchievement(id:string){if(!save.achievements.includes(id)){save.achievements.push(id);const item=achievements.find(x=>x[0]===id);if(item)notify(`업적 달성 · ${item[1]}`);}}
function notify(msg:string){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.append(el);window.setTimeout(()=>el.remove(),2300);}
function shell(content:string){
  app.innerHTML=`<div class="frame"><header class="topbar"><button class="brand" data-action="home"><span class="brand-mark">✣</span><span>DEVIL'S <b>VAULT</b></span></button><div class="top-meta"><span class="soul"><i>✦</i> ${money(save.soulCoins)} SOUL</span><button class="icon-btn" data-action="settings" aria-label="설정">⚙</button></div></header><div class="progress-strip"><span>JACKPOT GAUGE</span><div class="gauge"><i style="width:${save.jackpotGauge}%"></i></div><b>${save.jackpotGauge}%</b>${save.jackpotGauge>=100?'<em>FEVER READY</em>':''}</div>${content}<footer>ALL COINS ARE FICTIONAL · LOCAL SAVE ONLY <span>V.1.0</span></footer></div><div class="toast-wrap"></div>`;
  app.querySelectorAll<HTMLElement>('[data-action]').forEach(el=>el.addEventListener('click',()=>action(el.dataset.action!,el.dataset.id)));
  app.querySelectorAll<HTMLElement>('[data-chest]').forEach(el=>el.addEventListener('click',()=>selectChest(Number(el.dataset.chest))));
}
function renderMenu(){currentView='menu'; const best=save.statistics.bestStreak; shell(`<section class="hero"><div class="seal"><span>✣</span><i>THE SEALED VAULT</i></div><p class="eyebrow">A GAME OF GREED &amp; GRACE</p><h1>DEVIL'S<br><em>VAULT</em></h1><p class="subtitle">악마의 금고</p><p class="tagline">욕심을 버리면 살아나갈 수 있다.</p><button class="primary big" data-action="start">금고에 들어간다 <span>↗</span></button><div class="hero-stats"><div><b>${money(save.statistics.runs)}</b><small>총 RUN</small></div><div><b>${money(save.statistics.bestRun)} G</b><small>최고 획득</small></div><div><b>${best}</b><small>최고 연승</small></div></div></section><nav class="menu-grid"><button data-action="upgrades"><i>✦</i><span>영구 업그레이드</span><small>SOUL COIN 사용</small></button><button data-action="records"><i>▤</i><span>기록 보관실</span><small>전적과 업적</small></button><button data-action="settings"><i>⚙</i><span>설정</span><small>사운드 · 화면</small></button></nav><p class="notice">이 게임의 골드는 가상 재화이며 현금 가치가 없습니다.</p>`);
}
function beginIntro(){if(save.introSeen){chooseCharacter();return;}modal('어서 와라.','이곳의 규칙은 간단하다.<br>가져갈 수 있을 때 가져가라.<br><br>욕심을 부리는 순간…<br>모든 것을 잃게 될 테니.',`<button class="primary" data-modal="intro-go">금고 문을 연다</button><button class="quiet" data-modal="intro-skip">건너뛰기</button>`);}
function chooseCharacter(){modal('누구의 운명으로 들어갈 것인가?','플레이 스타일을 선택하세요.',`<div class="character-list">${CHARACTERS.map(c=>`<button class="character-card" data-character="${c.id}"><b>${c.icon} ${c.name}</b><span>${c.title}</span><small>${c.desc}</small></button>`).join('')}</div><button class="quiet" data-modal="close">돌아가기</button>`);}
function startRun(character:string){
  save.introSeen=true;save.statistics.runs++;const fever=save.jackpotGauge>=100;if(fever)save.jackpotGauge=0;
  run={gold:0,streak:0,round:1,chests:[],selected:null,revealed:false,relics:[],relicUsed:[],character,insuranceUsed:false,extraLifeUsed:false,doubleUsed:false,fever,pendingEscape:false,collected:[],treasureGoldBonus:0};
  if(save.upgrades.insurance)run.relics.push('insurance');
  nextRound();
}
function nextRound(){if(!run)return;run.round=run.streak+1;run.chests=createChests(save,run);run.selected=null;run.revealed=false;
 if(run.relics.includes('eye')&&!run.relicUsed.includes('eye')){const index=Math.floor(Math.random()*run.chests.length);const result=run.chests[index]!.result;run.chests[index]!.hint=`간파 · ${result.name??result.type.toUpperCase()}${result.amount?` · ${result.amount}`:''}`;run.relicUsed.push('eye');}
 if(run.relics.includes('thread')&&!run.relicUsed.includes('thread')){const index=run.chests.findIndex(chest=>chest.result.type==='ruin');if(index>=0){run.chests[index]!.hint='운명의 실 · RUIN';run.relicUsed.push('thread');}}
 currentView='game';renderGame();}
function renderGame(){if(!run)return;const risk=riskForRound(run.round,save,run);const fever=run.fever?'<span class="fever-tag">✦ FEVER</span>':'';const dangerClass=run.streak>=9?'extreme':run.streak>=7?'danger':'';
  shell(`<section class="game-area ${dangerClass}"><div class="game-heading"><div><p class="eyebrow">VAULT RUN · ROUND ${String(run.round).padStart(2,'0')}</p><h2>${run.streak>=9?'EXTREME GREED':run.streak>=7?'DANGER ZONE':'금고가 숨을 쉰다'}</h2></div>${fever}<button class="exit-small" data-action="menu">나가기</button></div><div class="hud"><div><small>현재 확보액</small><strong>${money(run.gold)} <i>G</i></strong></div><div><small>현재 배율</small><strong class="gold-text">×${multiplier().toFixed(2).replace(/0+$/,'').replace(/\.$/,'')}</strong></div><div><small>연속 성공</small><strong>${run.streak}<i>회</i></strong></div><div><small>이번 라운드 RUIN 위험도</small><strong class="risk-text">${risk.toFixed(1)}<i>%</i></strong></div></div><div class="vault-door"><div class="door-rings"></div><div class="chests">${run.chests.map((c,i)=>chestHtml(c,i)).join('')}</div><div class="door-sigil">✣</div></div><div class="action-panel">${run.revealed?revealActions():`<p>${run.streak===0?'세 개의 상자 중 하나를 선택하세요.':'연승을 이어갈 상자를 고르세요.'}</p><small>성공 시 보상과 배율이 상승합니다 · RUIN이면 보상을 모두 잃습니다</small>${run.streak>0?`<button class="escape-btn" data-action="escape">${money(run.gold)} G 들고 탈출</button>`:''}`}</div>${run.relics.length?`<div class="relic-bar"><span>보유 유물</span>${run.relics.map(id=>{const r=RELICS.find(x=>x.id===id);return r?`<span title="${r.text}" class="relic-chip">${r.icon} ${r.name}</span>`:''}).join('')}</div>`:''}${tutorialStep?`<div class="tutorial-hint"><span>${tutorialText()}</span><button data-action="tutorial-next">계속</button></div>`:''}</section>`);
}
function chestHtml(c:Chest,i:number){if(!run)return'';const reveal=run.revealed;const selected=run.selected===i;const r=c.result;let label='봉인된 상자',icon='?';if(reveal){icon=({gold:'G',multiplier:'×',treasure:'✦',relic:'♜',curse:'☠',ruin:'☠',jackpot:'★'} as Record<string,string>)[r.type];label=r.type==='gold'?`${money(r.amount??0)} G`:r.type==='multiplier'?`×${r.amount}`:r.type==='ruin'?'RUIN':r.type==='curse'?`${r.name} · ${r.detail}`:r.type==='relic'?r.name??'유물':r.name??'JACKPOT';if(r.type==='treasure'||r.type==='jackpot')label+=` +${money(rewardValue(r,save,run))} G`;}
 const clue=c.hint??c.clue;const hint=clue.includes('예언자의 빛')?'seer-safe':clue.includes('RUIN')?'danger-hint':'';
 return `<button class="chest ${reveal?'revealed '+r.type:''} ${selected?'selected':''} ${hint}" data-chest="${i}" ${reveal?'disabled':''}><span class="chest-top">${icon}</span><span class="chest-body"><b>${reveal?label:`금고 ${String.fromCharCode(65+i)}`}</b></span><small>${reveal?'':clue}</small>${selected?'<i class="picked">선택</i>':''}</button>`;}
function revealActions(){if(!run)return'';const c=run.chests[run.selected??0]!.result;const label=c.type==='ruin'?(run.insuranceUsed||run.extraLifeUsed?'위기를 막아냈다!':'RUIN · 모든 것을 잃었다'):c.type==='curse'?`저주 · ${c.detail}`:c.type==='jackpot'?`JACKPOT · +${money(rewardValue(c,save,run))} G`:c.type==='multiplier'?`배율 상승 · ×${c.amount}`:c.type==='relic'?`유물 획득 · ${c.name}`:`${c.name??'보상'} · +${money(rewardValue(c,save,run))} G`;
 return `<div class="result-callout ${c.type}"><b>${label}</b><small>다른 상자의 실제 결과도 공개되었습니다.</small></div><div class="post-choice"><button class="primary" data-action="continue">다음 상자 도전 <span>→</span></button><button class="escape-btn" data-action="escape">${money(run.gold)} G 확정하고 탈출</button></div>`;}
function selectChest(index:number){if(!run||run.revealed||!run.chests[index])return;run.selected=index;const chest=run.chests[index]!;
  if(run.relics.includes('coin')&&!run.relicUsed.includes('coin')){run.relicUsed.push('coin');const safe=run.chests.findIndex((c,i)=>i!==index&&c.result.type!=='ruin');if(safe>=0&&chest.result.type==='ruin'){run.selected=safe;notify('검은 동전이 선택을 바꾸었습니다.');}}
  resolveChest();}
function resolveChest(){if(!run)return;run.revealed=true;const result=run.chests[run.selected??0]!.result;
 if(result.type==='ruin'){
   if(run.relics.includes('insurance')&&!run.insuranceUsed){run.insuranceUsed=true;result.type='curse';result.name='보험 발동';result.detail='보상을 지켰습니다';addAchievement('not_today');}
   else if(run.character==='immortal'&&!run.extraLifeUsed){run.extraLifeUsed=true;result.type='curse';result.name='불사의 심장';result.detail='죽음에서 한 번 돌아왔습니다';}
   else {finishRun('ruin');return;}
 }
 run.streak++;save.statistics.bestStreak=Math.max(save.statistics.bestStreak,run.streak);
 if(result.type==='gold'||result.type==='treasure'||result.type==='jackpot'){let value=rewardValue(result,save,run);if(run.treasureGoldBonus){value+=run.treasureGoldBonus;run.treasureGoldBonus=0;}run.gold+=value;run.collected.push(result.name??'금화');if(result.type==='jackpot'){save.statistics.jackpots++;save.jackpotGauge=Math.min(100,save.jackpotGauge+12);}}
 if(result.type==='multiplier')run.gold=Math.round(Math.max(run.gold,100)*(result.amount??1));
 if(result.type==='curse'){if(result.detail?.includes('20%'))run.gold=Math.floor(run.gold*.8);else if(result.detail?.includes('배율'))run.streak=Math.max(0,run.streak-1);else save.jackpotGauge=Math.min(100,save.jackpotGauge+2);run.collected.push(`저주: ${result.detail}`);}
 if(result.type==='relic'&&result.detail&&!run.relics.includes(result.detail))run.relics.push(result.detail);
 if(run.relics.includes('hand')&&result.type==='gold'&&!run.relicUsed.includes('hand'))run.relicUsed.push('hand');
 if(run.relics.includes('eye')&&!run.relicUsed.includes('eye')){run.relicUsed.push('eye');const selected=run.selected;const next=run.chests.findIndex((_,i)=>i!==selected);if(next>=0)run.chests[next]!.hint=`${run.chests[next]!.result.type.toUpperCase()} · ${run.chests[next]!.result.name??''}`;}
 if(run.streak>=5)save.jackpotGauge=Math.min(100,save.jackpotGauge+1);if(run.streak>=5)addAchievement('high_roller');persist();renderGame();if(result.type==='jackpot'&&save.settings.shake&&!save.settings.reducedMotion){app.classList.add('jackpot-flash');window.setTimeout(()=>app.classList.remove('jackpot-flash'),600);}playTone(result.type==='jackpot'?880:result.type==='curse'?170:550,result.type==='jackpot'?0.5:0.12);
}
function finishRun(kind:'escape'|'ruin'){if(!run)return;resultKind=kind;currentView='result';const stats=save.statistics;let coins=0;
 if(kind==='escape'){stats.escapes++;const ringPenalty=run.relics.includes('ring') ? 0.9 : 1;const amount=Math.floor(run.gold/1000*ringPenalty);coins=Math.max(1,amount);save.soulCoins+=coins;stats.lifetimeGold+=run.gold;stats.bestRun=Math.max(stats.bestRun,run.gold);save.jackpotGauge=Math.min(100,save.jackpotGauge+Math.min(18,run.streak*1.3));if(run.streak===1)addAchievement('coward');if(!save.achievements.includes('first_escape'))addAchievement('first_escape');if(stats.lifetimeGold>=1_000_000)addAchievement('millionaire');}
 else {stats.ruins++;save.jackpotGauge=Math.min(100,save.jackpotGauge+12);}
 persist();renderResult(coins);
}
function renderResult(coins:number){if(!run)return;const esc=resultKind==='escape';shell(`<section class="result-screen ${esc?'escaped':'ruined'}"><div class="result-seal">${esc?'✧':'☠'}</div><p class="eyebrow">${esc?'THE DOOR OPENS':'THE VAULT CLAIMS YOU'}</p><h1>${esc?'ESCAPED':'RUIN'}</h1><p class="result-sub">${esc?'당신은 금고를 빠져나왔다.':'악마가 당신의 탐욕을 가져갔습니다.'}</p><div class="result-number"><strong>${money(esc?run.gold:0)}</strong><span>G ${esc?'획득':'소실'}</span></div>${esc?`<div class="soul-earned">✦ SOUL COIN <b>+${coins}</b></div>`:''}<div class="result-stats"><div><b>${run.streak}</b><small>최고 연승</small></div><div><b>×${multiplier().toFixed(1)}</b><small>최고 배율</small></div><div><b>${run.collected.length}</b><small>발견 보상</small></div><div><b>${run.relics.length}</b><small>획득 유물</small></div></div>${run.collected.length?`<div class="loot-list"><b>이번 RUN의 기록</b><span>${run.collected.slice(-5).join(' · ')}</span></div>`:''}<div class="result-actions"><button class="primary" data-action="start">다시 도전 <span>↗</span></button><button class="secondary" data-action="upgrades">업그레이드</button><button class="quiet" data-action="home">메인으로</button></div></section>`);}
function escapeRun(){if(!run||run.streak===0)return;run.pendingEscape=true;if(!run.doubleUsed&&Math.random()<.28){modal('😈 마지막 제안','<b>DOUBLE OR NOTHING</b><br><br>성공하면 보상이 두 배.<br>실패하면 모두 잃습니다.<br><br><span class="risk-text">성공 확률 50%</span>',`<button class="primary" data-modal="double">계약한다</button><button class="secondary" data-modal="escape">거절하고 탈출</button>`);return;}finishRun('escape');}
function doDouble(){if(!run)return;run.doubleUsed=true;if(Math.random()<.5){run.gold*=2;save.statistics.doubleWins++;addAchievement('deal');notify('계약 성공 · 보상이 두 배!');finishRun('escape');}else{run.gold=0;finishRun('ruin');}}
function renderUpgrades(){currentView='upgrades';shell(`<section class="subpage"><button class="back" data-action="home">← 돌아가기</button><p class="eyebrow">PERMANENT PACTS</p><h1>영구 업그레이드</h1><p class="subcopy">탈출 보상으로 얻은 SOUL COIN을 사용합니다.</p><div class="upgrade-list">${BALANCE.upgrades.map(u=>{const lv=save.upgrades[u.id]??0;const cost=u.cost[lv];return `<article class="upgrade-card"><div class="upgrade-icon">✦</div><div class="upgrade-copy"><h3>${u.name}</h3><p>${u.desc}</p><small>LEVEL ${lv} / ${u.max}</small><div class="level-track">${Array.from({length:u.max},(_,i)=>`<i class="${i<lv?'filled':''}"></i>`).join('')}</div></div><button class="buy-btn" data-action="buy" data-id="${u.id}" ${cost===undefined||save.soulCoins<cost?'disabled':''}>${cost===undefined?'MAX':`✦ ${cost}`}</button></article>`;}).join('')}</div></section>`);}
function buyUpgrade(id:string){const u=BALANCE.upgrades.find(x=>x.id===id);if(!u)return;const lv=save.upgrades[id]??0;const cost=u.cost[lv];if(cost===undefined||save.soulCoins<cost)return;save.soulCoins-=cost;save.upgrades[id]=lv+1;persist();renderUpgrades();}
function renderRecords(){currentView='records';const s=save.statistics;shell(`<section class="subpage"><button class="back" data-action="home">← 돌아가기</button><p class="eyebrow">ARCHIVE OF SOULS</p><h1>기록 보관실</h1><div class="record-grid">${[['총 RUN',s.runs],['탈출 성공',s.escapes],['RUIN',s.ruins],['최고 연승',s.bestStreak],['최고 RUN 골드',`${money(s.bestRun)} G`],['JACKPOT',s.jackpots],['누적 골드',`${money(s.lifetimeGold)} G`],['더블 성공',s.doubleWins]].map(([a,b])=>`<div><small>${a}</small><b>${b}</b></div>`).join('')}</div><h2 class="section-heading">업적 <span>${save.achievements.length}/${achievements.length}</span></h2><div class="achievement-grid">${achievements.map(([id,name,desc])=>`<div class="achievement ${save.achievements.includes(id)?'unlocked':''}"><i>${save.achievements.includes(id)?'✦':'◇'}</i><b>${name}</b><small>${desc}</small></div>`).join('')}</div><h2 class="section-heading">운명 선택</h2><div class="unlocks">${CHARACTERS.map(c=>`<span>${c.icon} ${c.name}</span>`).join('')}</div></section>`);}
function renderSettings(){currentView='settings';shell(`<section class="subpage settings-page"><button class="back" data-action="home">← 돌아가기</button><p class="eyebrow">VAULT SETTINGS</p><h1>설정</h1>${settingRow('sound','효과음','간단한 보상 효과음')}${settingRow('shake','화면 흔들림','큰 보상에서 화면 흔들림')}${settingRow('reducedMotion','움직임 줄이기','애니메이션을 줄입니다')}<button class="secondary wide" data-action="tutorial-reset">튜토리얼 다시 보기</button><button class="danger-button wide" data-action="reset">저장 데이터 초기화</button></section>`);}
function settingRow(key:keyof Settings,label:string,desc:string){return `<label class="setting-row"><span><b>${label}</b><small>${desc}</small></span><input type="checkbox" data-setting="${key}" ${save.settings[key]?'checked':''}></label>`;}
function tutorialText(){return ['상자 단서를 살펴보고 하나를 고르세요.','성공하면 보상이 쌓이고 연승 배율이 올라갑니다.','RUIN을 고르면 확보한 보상을 전부 잃습니다.','현재 보상을 들고 탈출할 수도 있습니다.'][tutorialStep-1]??'욕심을 부릴지, 살아서 나갈지는 당신의 선택입니다.';}
function modal(title:string,body:string,buttons:string){document.querySelector('.modal-layer')?.remove();const div=document.createElement('div');div.className='modal-layer';div.innerHTML=`<div class="modal"><div class="modal-mark">✣</div><h2>${title}</h2><p>${body}</p><div class="modal-actions">${buttons}</div></div>`;document.body.append(div);div.querySelectorAll<HTMLElement>('[data-modal]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.modal;div.remove();if(action==='intro-go'||action==='intro-skip'){save.introSeen=true;chooseCharacter();}else if(action==='home')renderMenu();else if(action==='close'){}else if(action==='escape')finishRun('escape');else if(action==='double')doDouble();}));div.querySelectorAll<HTMLElement>('[data-character]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.character!;div.remove();if(!save.tutorialCompleted){tutorialStep=1;save.tutorialCompleted=true;}startRun(id);}));}
function action(name:string,id?:string){switch(name){case'home':renderMenu();break;case'start':beginIntro();break;case'upgrades':renderUpgrades();break;case'records':renderRecords();break;case'settings':renderSettings();break;case'menu':modal('금고에서 나갈까요?','이번 RUN의 미확정 보상은 사라집니다.',`<button class="danger-button" data-modal="home">나가기</button><button class="quiet" data-modal="close">계속하기</button>`);break;case'continue':if(run){if(tutorialStep&&tutorialStep<4){tutorialStep++;}else tutorialStep=0;nextRound();}break;case'escape':escapeRun();break;case'buy':buyUpgrade(id??'');break;case'tutorial-next':if(tutorialStep<4){tutorialStep++;renderGame();}else{tutorialStep=0;renderGame();}break;case'tutorial-reset':save.tutorialCompleted=false;persist();notify('다음 RUN부터 튜토리얼이 표시됩니다.');break;case'reset':modal('저장 데이터를 지울까요?','모든 기록, 업그레이드, SOUL COIN이 초기화됩니다.',`<button class="danger-button" data-modal="reset-confirm">모두 초기화</button><button class="quiet" data-modal="close">취소</button>`);document.querySelector('[data-modal="reset-confirm"]')?.addEventListener('click',()=>{save=SaveManager.reset();document.querySelector('.modal-layer')?.remove();renderMenu();});break;}}
function playTone(freq:number,duration:number){if(!save.settings.sound)return;try{const ctx=new AudioContext();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=freq;osc.type='sine';gain.gain.setValueAtTime(.04,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+duration);osc.onended=()=>void ctx.close();}catch{/* audio is optional */}}
app.addEventListener('change',(event)=>{const input=event.target as HTMLInputElement;const key=input.dataset.setting as keyof Settings|undefined;if(key){save.settings[key]=input.checked;if(key==='reducedMotion')document.documentElement.classList.toggle('reduce-motion',input.checked);persist();}});
app.addEventListener('click',(event)=>{const el=(event.target as HTMLElement).closest('.chest');if(el&&!el.hasAttribute('data-chest'))return;});
window.addEventListener('keydown',e=>{if(e.key==='Escape'){document.querySelector('.modal-layer')?.remove();if(currentView==='game')renderGame();}});
renderMenu();
