import Phaser from 'phaser';
import './style.css';
import { BALANCE, CHARACTERS, RELICS, rewardValue, type Chest, type RunState, type Settings } from './game/balance';
import { createChests, applyReward } from './game/systems/RewardManager';
import { createRun, trackFloor, trackChest } from './game/systems/RunManager';
import { FloorManager } from './game/systems/FloorManager';
import { ChestTierManager } from './game/systems/ChestTierManager';
import { VaultFlow } from './game/systems/VaultFlow';
import { floorHud, roomHeading, decisionHtml, summaryHtml, depthRecords } from './game/ui/vault';
import { SaveManager } from './game/save';
import { icon, sigil, vaultArt, chestArt } from './game/ui/art';

class Atmosphere extends Phaser.Scene {
  private dust!: Phaser.GameObjects.Particles.ParticleEmitter;
  private backdrop?: Phaser.GameObjects.Graphics;
  constructor(){super('atmosphere');}
  create(){
    const {width,height}=this.scale;
    const g=this.add.graphics();
    g.fillGradientStyle(0x1b100e,0x100c0b,0x090807,0x090807,1); g.fillRect(0,0,width,height);
    for(let i=0;i<8;i++){this.add.circle(width*.12+i*width*.11,height*.23+Math.sin(i)*40,2+i%3,0xffb253,.16).setBlendMode(Phaser.BlendModes.ADD);}
    const pixel=this.add.graphics();pixel.fillStyle(0xffffff);pixel.fillRect(0,0,4,4);pixel.generateTexture('pixel',4,4);pixel.destroy();
    this.dust=this.add.particles(0,0,'pixel',{color:[0xffb253,0xb33d24,0x73422d],alpha:{start:.36,end:0},scale:{start:2,end:.3},speed:{min:3,max:16},angle:{min:250,max:290},lifespan:7000,frequency:260,quantity:1,blendMode:Phaser.BlendModes.ADD});
    this.dust.setDepth(1); this.scale.on('resize',()=>this.draw()); this.draw();
  }
  draw(){ const g=this.backdrop??(this.backdrop=this.add.graphics());g.clear();g.fillStyle(0x4b2117,.34);g.fillEllipse(this.scale.width/2,this.scale.height*.48,Math.min(900,this.scale.width*.9),Math.min(560,this.scale.height*.7));g.lineStyle(1,0xb47a39,.18);g.strokeEllipse(this.scale.width/2,this.scale.height*.48,Math.min(900,this.scale.width*.9),Math.min(560,this.scale.height*.7));g.setDepth(0); }
  update(_t:number,_dt:number){this.dust?.forEachAlive(p=>{p.y-=.04;},this);}
}
const game=new Phaser.Game({type:Phaser.CANVAS,parent:'ambient',backgroundColor:'#100c0b',transparent:false,scale:{mode:Phaser.Scale.RESIZE,width:window.innerWidth,height:window.innerHeight},scene:[Atmosphere],render:{antialias:true,roundPixels:true},fps:{target:30,forceSetTimeOut:true}});
void game;

const app=document.querySelector<HTMLElement>('#app')!;
let save=SaveManager.load();
document.documentElement.classList.toggle('reduce-motion',save.settings.reducedMotion);
let run:RunState|null=null;
let currentView:'menu'|'game'|'result'|'upgrades'|'records'|'settings'='menu';
let resultKind:'escape'|'ruin'='escape';
let tutorialStep=0;
let displayedGold=0;
const achievements=[['first_escape','첫 탈출','첫 탈출 성공'],['high_roller','고위험 투자자','5연승 달성'],['coward','신중한 생존자','첫 라운드 탈출'],['millionaire','백만장자','누적 1,000,000G'],['deal','악마와의 거래','Double or Nothing 성공'],['not_today','오늘은 안 돼','RUIN을 보험으로 방어']];
achievements.push(['going_deeper','Going Deeper','B3 최초 도달'],['welcome_hell','Welcome to Hell','B5 최초 도달'],['treasure_hunter','Treasure Hunter','LEGENDARY 상자 10개 열기'],['forbidden_vault','Forbidden Vault','MYTHIC 상자 최초 열기'],['blood_money','Blood Money','피의 특수 금고에서 살아남고 탈출'],['explorer','Explorer','모든 특수 금고방 발견'],['no_fear','No Fear','하나의 RUN에서 B5까지 도달']);
const money=(n:number)=>Math.floor(n).toLocaleString('ko-KR');
const multiplier=()=>run?BALANCE.multipliers[Math.min(run.streak,BALANCE.multipliers.length-1)]!*(1+(save.upgrades.greed??0)*.04)*(run.relics.includes('ring')?1.3:1)*(run.fever?1.25:1):1;
const persist=()=>SaveManager.save(save);
function addAchievement(id:string){if(!save.achievements.includes(id)){save.achievements.push(id);const item=achievements.find(x=>x[0]===id);if(item)notify(`업적 달성 · ${item[1]}`);}}
function notify(msg:string){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.append(el);window.setTimeout(()=>el.remove(),2300);}
const flow=new VaultFlow({run:()=>run,save:()=>save,active:()=>currentView==='game',render:renderGame,deal:nextRound,persist,notify,achievement:addAchievement,tone:playTone});
function shell(content:string){
 document.documentElement.dataset.floor=currentView==='game'&&run?(run.activeSpecial?({gold:'greed',blood:'blood',cursed:'cursed',relic:'forgotten',shop:'devil'} as const)[run.activeSpecial]:FloorManager.definition(run).id):'';
  app.innerHTML=`<div class="frame"><header class="topbar"><button class="brand" data-action="home" aria-label="악마의 금고 메인으로">${sigil()}<span>DEVIL'S VAULT<small>악마의 금고</small></span></button><div class="top-meta"><span class="soul">${icon('coin')}<b>${money(save.soulCoins)}</b><small>SOUL COIN</small></span><button class="icon-btn" data-action="settings" aria-label="설정">${icon('settings')}</button></div></header><div class="progress-strip"><span>${icon('flame')} JACKPOT</span><div class="gauge"><i style="width:${save.jackpotGauge}%"></i></div><b>${save.jackpotGauge}<small>%</small></b><em>${save.jackpotGauge>=100?'FEVER READY':'금고의 각성'}</em></div>${content}<footer><span class="footer-seal">✧</span> ALL COINS ARE FICTIONAL · LOCAL SAVE ONLY <span class="version">DEEP VAULTS · 2.0</span></footer></div>`;
  app.querySelectorAll<HTMLElement>('[data-action]').forEach(el=>el.addEventListener('click',()=>action(el.dataset.action!,el.dataset.id)));
  app.querySelectorAll<HTMLElement>('[data-chest]').forEach(el=>el.addEventListener('click',()=>selectChest(Number(el.dataset.chest))));
  app.querySelectorAll<HTMLElement>('[data-count]').forEach(el=>{
    const target=Number(el.dataset.count),from=Number(el.dataset.from??0);
    if(save.settings.reducedMotion){el.textContent=money(target);return;}
    const start=performance.now();
    function tick(now:number){if(!el.isConnected)return;const p=Math.min(1,(now-start)/650);el.textContent=money(from+(target-from)*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick);}
    requestAnimationFrame(tick);
  });
}

function renderMenu(){flow.cancel();currentView='menu'; const best=save.statistics.bestStreak; shell(`<section class="hero"><div class="hero-copy"><p class="eyebrow"><span></span> ENTER AT YOUR OWN RISK</p><h1>DEVIL'S<br><em>VAULT</em></h1><p class="subtitle">악마의 금고</p><div class="hero-divider"></div><p class="tagline">금화는 쌓이고, 욕심은 깊어진다.<br><strong>살아서 나갈 수 있을 때 가져가라.</strong></p><button class="primary big" data-action="start">금고에 들어간다 ${icon('arrow')}</button><p class="start-note">다섯 개의 층. 더 큰 보물. 더 깊은 탐욕.</p></div><div class="hero-art"><div class="art-halo"></div>${vaultArt()}<div class="art-caption"><span>NO. 0666</span><i>THE SEAL REMAINS UNBROKEN</i></div></div></section><div class="hero-stats"><div><small>지금까지의 도전</small><b>${money(save.statistics.runs)} <i>RUNS</i></b></div><div><small>최고 탈출 보상</small><b>${money(save.statistics.bestRun)} <i>G</i></b></div><div><small>최고 연속 성공</small><b>${best} <i>STREAK</i></b></div></div><nav class="menu-grid" aria-label="게임 메뉴"><button data-action="upgrades">${icon('upgrade')}<span><b>영구 업그레이드</b><small>영혼을 바쳐 운명을 바꾼다</small></span>${icon('arrow')}</button><button data-action="records">${icon('records')}<span><b>기록 보관실</b><small>금고에 새겨진 당신의 흔적</small></span>${icon('arrow')}</button><button data-action="settings">${icon('settings')}<span><b>설정</b><small>사운드와 화면 조정</small></span>${icon('arrow')}</button></nav><div class="rules-strip"><span>금고의 법칙</span><p><b>01</b> 상자를 고른다</p><p><b>02</b> 보상을 쌓는다</p><p><b>03</b> 잃기 전에 탈출한다</p></div>`);
}

function beginIntro(){if(save.introSeen){chooseCharacter();return;}modal('어서 와라.','이곳의 규칙은 간단하다.<br>가져갈 수 있을 때 가져가라.<br><br>욕심을 부리는 순간…<br>모든 것을 잃게 될 테니.',`<button class="primary" data-modal="intro-go">금고 문을 연다</button><button class="quiet" data-modal="intro-skip">건너뛰기</button>`);}
function chooseCharacter(){modal('누구의 운명으로 들어갈 것인가?','능력을 읽고, 당신의 계약자를 선택하세요.',`<div class="character-list">${CHARACTERS.map((c,i)=>`<button class="character-card character-${c.id}" data-character="${c.id}"><div class="character-emblem">${icon(['card','eye','crown','skull'][i]!)}<span>${String(i+1).padStart(2,'0')}</span></div><b>${c.name}</b><span>${c.title}</span><small>${c.desc}</small><i>이 운명을 선택 ${icon('arrow')}</i></button>`).join('')}</div><button class="quiet" data-modal="close">돌아가기</button>`);}

function startRun(character:string){
  flow.cancel();displayedGold=0;save.introSeen=true;save.statistics.runs++;const fever=save.jackpotGauge>=100;if(fever)save.jackpotGauge=0;
  run=createRun(character,fever);trackFloor(save,run);persist();
  if(save.upgrades.insurance)run.relics.push('insurance');
  nextRound();
}
function nextRound(){if(!run||run.phase==='ended')return;run.chests=createChests(save,run);run.selected=null;run.revealed=false;currentView='game';renderGame();}
function renderGame(){if(!run)return;const risks=run.chests.map(c=>c.ruinChance);const risk=Math.max(0,...risks);const low=Math.min(...risks);const riskLabel=low===risk?risk.toFixed(1):`${low.toFixed(1)}–${risk.toFixed(1)}`;const fever=run.fever?'<span class="fever-tag">✦ FEVER MODE</span>':'';const dangerClass=run.streak>=9?'extreme':run.streak>=7?'danger':'';const character=CHARACTERS.find(c=>c.id===run!.character);
  if(['floor-clear','final-choice','special-offer'].includes(run.phase)||(run.phase==='special'&&run.activeSpecial==='shop')){shell(`<section class="game-area">${floorHud(run)}${decisionHtml(run)}</section>`);displayedGold=run.gold;return;}
  shell(`<section class="game-area ${dangerClass}">${floorHud(run)}${roomHeading(run)}<div class="game-heading"><div><p class="eyebrow">THE INNER VAULT <span> / </span> ROUND ${String(run.round).padStart(2,'0')}</p><h2>${run.phase==='final'?'악마의 마지막 봉인':run.streak>=9?'끝을 모르는 탐욕':run.streak>=7?'금고가 당신을 노린다':'어느 봉인을 풀 것인가?'}</h2></div><div class="run-identity">${fever}<span>${character?.name??'계약자'}</span><button class="exit-small" data-action="menu">${icon('exit')} 나가기</button></div></div><div class="hud"><div class="hud-gold"><small>잃을 수도 있는 보상</small><strong><span data-count="${run.gold}" data-from="${displayedGold}">${money(run.gold)}</span><i>G</i></strong></div><div><small>보상 배율</small><strong class="gold-text">×${multiplier().toFixed(2).replace(/0+$/,'').replace(/\.$/,'')}</strong></div><div><small>연속 성공</small><strong>${run.streak}<i>회</i></strong></div><div class="hud-risk"><small>${icon('skull')} 상자별 RUIN 범위</small><strong class="risk-text">${riskLabel}<i>%</i></strong><div class="risk-track"><i style="width:${risk}%"></i></div></div></div><div class="vault-door"><div class="room-arch"></div><div class="room-rune">${sigil()}</div><div class="room-caption">${run.phase==='final'?'THE LAST SEAL · ONE FATE':'THREE SEALS · ONE FATE'}</div><div class="candles candle-left"><i></i><i></i><i></i></div><div class="candles candle-right"><i></i><i></i><i></i></div><div class="chests ${run.phase==='final'?'final-chests':''}">${run.chests.map((c,i)=>chestHtml(c,i)).join('')}</div><div class="floor-line"></div></div><div class="action-panel">${run.revealed?revealActions():`<div class="choice-prompt">${icon('lock')}<div><p>${run.streak===0?'상자를 눌러 첫 번째 봉인을 푸세요.':'단서를 읽고, 다음 상자를 고르세요.'}</p><small>RUIN을 선택하면 미확정 보상을 모두 잃습니다.</small></div></div>${run.completedRounds>0||run.streak>0?`<button class="escape-btn" data-action="escape">${icon('exit')} ${money(run.gold)} G 들고 탈출</button>`:''}`}</div><div class="relic-bar"><span class="relic-label">${icon('upgrade')} 이번 RUN의 유물</span>${run.relics.length?run.relics.map(id=>{const r=RELICS.find(x=>x.id===id);return r?`<span title="${r.text}" class="relic-chip">${r.icon} ${r.name}</span>`:''}).join(''):'<small>봉인 상자에서 특별한 힘을 발견할 수 있습니다.</small>'}</div>${tutorialStep?`<div class="tutorial-hint"><b>0${tutorialStep}</b><span>${tutorialText()}</span><button data-action="tutorial-next">확인 ${icon('arrow')}</button></div>`:''}</section>`);
  displayedGold=run.gold;
}

function chestHtml(c:Chest,i:number){if(!run)return'';const reveal=run.revealed;const selected=run.selected===i;const r=c.result;const tier=ChestTierManager.definition(c.tier);let label='봉인된 상자',symbol='lock';if(reveal){symbol=({gold:'coin',multiplier:'upgrade',treasure:'crown',relic:'eye',curse:'skull',ruin:'skull',jackpot:'flame'} as Record<string,string>)[r.type]!;label=r.type==='gold'?`${money(selected&&c.payout!==undefined?c.payout:rewardValue(r,save,run))} G`:r.type==='multiplier'?`×${r.amount}`:r.type==='ruin'?'RUIN':r.type==='curse'?r.name??'저주':r.name??'보상';}
 const clue=c.hint??c.clue;const hint=clue.includes('예언자의 빛')?'seer-safe':clue.includes('RUIN')?'danger-hint':'';
 return `<button style="--tier-color:${tier.color}" class="chest tier-${c.tier} ${reveal?'revealed '+r.type:''} ${selected?'selected':''} ${hint}" data-chest="${i}" ${reveal?'disabled':''} aria-label="${reveal?label:tier.name+' · RUIN '+c.ruinChance.toFixed(1)+'% · '+clue}"><span class="chest-index">SEAL ${String.fromCharCode(65+i)} <i>${selected?'당신의 선택':reveal?'선택하지 않은 상자':'미확인'}</i></span><span class="tier-label">${c.tier.toUpperCase()}</span><span class="chest-visual">${chestArt(reveal?r.type:'sealed',reveal,c.tier)}${reveal?`<span class="chest-result-icon">${icon(symbol)}</span>`:''}</span><span class="chest-body"><b>${reveal?label:run.activeSpecial==='relic'?r.name:tier.name}</b>${reveal&&(r.type==='treasure'||r.type==='jackpot')?`<span>+${money(selected&&c.payout!==undefined?c.payout:rewardValue(r,save,run))} G</span>`:''}</span><small class="chest-risk">RUIN ${c.ruinChance.toFixed(1)}%${c.tier==='mythic'?' · 봉인 주의':''}</small><small class="chest-clue"><i></i>${reveal?(r.type==='curse'?r.detail??'위험한 기운':selected?'봉인이 풀렸습니다':'실제 상자 결과'):clue}</small></button>`;}

function revealActions(){if(!run)return'';const selected=run.chests[run.selected??0]!;const c=selected.result;const label=c.type==='curse'?`${c.name} · ${c.detail}`:c.type==='jackpot'?`JACKPOT · +${money(selected.payout??rewardValue(c,save,run))} G`:c.type==='multiplier'?`배율 상승 · ×${c.amount}`:c.type==='relic'?`유물 획득 · ${c.name}`:`${c.name??'보상'} · +${money(selected.payout??rewardValue(c,save,run))} G`;
 if(run.phase==='final')return `<div class="result-callout"><b>${label}</b></div><button class="primary" data-action="escape">마지막 보상을 들고 떠난다 ${icon('exit')}</button>`;
 return `<div class="result-callout ${c.type}"><span>${icon(c.type==='curse'?'skull':c.type==='jackpot'?'flame':'coin')}</span><div><b>${label}</b><small>여기서 나갈 것인가, 한 번 더 열 것인가?</small></div></div><div class="post-choice"><button class="primary" data-action="continue">${run.phase==='special'?'금고방을 나와 계속':'한 번 더 도전'} ${icon('arrow')}</button><button class="escape-btn" data-action="escape">${icon('exit')} ${money(run.gold)} G 확정 탈출</button></div>`;}

function selectChest(index:number){if(!run||run.revealed||flow.busy||run.pendingEscape||!['normal','special','final'].includes(run.phase)||!run.chests[index]||run.activeSpecial==='shop')return;run.selected=index;const chest=run.chests[index]!;
  if(run.relics.includes('coin')&&!run.relicUsed.includes('coin')){const safe=run.chests.findIndex((c,i)=>i!==index&&c.result.type!=='ruin');if(safe>=0&&chest.result.type==='ruin'){run.relicUsed.push('coin');run.selected=safe;notify('검은 동전이 선택을 바꾸었습니다.');}}
  resolveChest();}
function resolveChest(){if(!run)return;run.revealed=true;const selectedChest=run.chests[run.selected??0]!;const result=selectedChest.result;trackChest(save,run).forEach(addAchievement);
 if(result.type==='ruin'){
   if(run.relics.includes('insurance')&&!run.insuranceUsed){run.insuranceUsed=true;result.type='curse';result.name='보험 발동';result.detail='보상을 지켰습니다';addAchievement('not_today');}
   else if(run.character==='immortal'&&!run.extraLifeUsed){run.extraLifeUsed=true;result.type='curse';result.name='불사의 심장';result.detail='죽음에서 한 번 돌아왔습니다';}
   else {finishRun('ruin');return;}
 }
 run.streak++;save.statistics.bestStreak=Math.max(save.statistics.bestStreak,run.streak);
 selectedChest.payout=applyReward(result,save,run);
 if(result.type==='jackpot'){save.statistics.jackpots++;save.jackpotGauge=Math.min(100,save.jackpotGauge+12);}
 flow.afterChest();
 if(run.streak>=5)save.jackpotGauge=Math.min(100,save.jackpotGauge+1);if(run.streak>=5)addAchievement('high_roller');persist();renderGame();if(result.type==='jackpot'&&save.settings.shake&&!save.settings.reducedMotion){app.classList.add('jackpot-flash');window.setTimeout(()=>app.classList.remove('jackpot-flash'),600);}playTone(result.type==='jackpot'?880:result.type==='curse'?170:350+['common','uncommon','rare','epic','legendary','mythic'].indexOf(selectedChest.tier)*100,result.type==='jackpot'?0.5:selectedChest.tier==='mythic'?.4:.12);
}
function finishRun(kind:'escape'|'ruin'){if(!run||run.phase==='ended')return;flow.cancel();run.phase='ended';run.pendingEscape=false;resultKind=kind;currentView='result';const stats=save.statistics;let coins=0;
 if(kind==='escape'){stats.escapes++;if(run.bloodSurvived)addAchievement('blood_money');if(run.relics.includes('ring'))run.gold=Math.floor(run.gold*.9);const amount=Math.floor(run.gold/1000);coins=Math.max(1,amount);save.soulCoins+=coins;stats.lifetimeGold+=run.gold;stats.bestRun=Math.max(stats.bestRun,run.gold);save.jackpotGauge=Math.min(100,save.jackpotGauge+Math.min(18,run.streak*1.3));if(run.streak===1)addAchievement('coward');if(!save.achievements.includes('first_escape'))addAchievement('first_escape');if(stats.lifetimeGold>=1_000_000)addAchievement('millionaire');}
 else {stats.ruins++;save.jackpotGauge=Math.min(100,save.jackpotGauge+12);}
 persist();renderResult(coins);
}
function renderResult(coins:number){if(!run)return;const esc=resultKind==='escape';shell(`<section class="result-screen ${esc?'escaped':'ruined'}"><div class="result-seal">${sigil()}<span>${icon(esc?'shield':'skull')}</span></div><p class="eyebrow">${esc?'YOUR SOUL IS STILL YOURS':'GREED ALWAYS HAS A PRICE'}</p><h1>${esc?'ESCAPED':'RUIN'}</h1><p class="result-sub">${esc?'금고의 문이 열렸다. 당신은 살아 돌아왔다.':'악마가 당신의 탐욕을 가져갔습니다.'}</p>${!esc?`<p class="lost-amount">${money(run.gold)} G <span>→</span> 0 G</p>`:''}<div class="result-number"><strong data-count="${esc?run.gold:0}">${money(esc?run.gold:0)}</strong><span>G</span></div>${esc?`<div class="soul-earned">${icon('coin')}<span>SOUL COIN<small>영구 업그레이드에 사용할 영혼</small></span><b>+${coins}</b></div>`:'<p class="ruin-note">실패도 금고를 깨웁니다. JACKPOT 게이지가 충전되었습니다.</p>'}<div class="result-stats"><div><small>연속 성공</small><b>${run.streak}<i> 회</i></b></div><div><small>보상 배율</small><b>×${multiplier().toFixed(1)}</b></div><div><small>발견 보상</small><b>${run.collected.length}<i> 개</i></b></div><div><small>획득 유물</small><b>${run.relics.length}<i> 개</i></b></div></div>${summaryHtml(run)}${run.collected.length?`<div class="loot-list"><b>이번 RUN의 흔적</b><span>${run.collected.slice(-5).join(' · ')}</span></div>`:''}<div class="result-actions"><button class="primary" data-action="start">다시 금고로 ${icon('arrow')}</button><button class="secondary" data-action="upgrades">${icon('upgrade')} 업그레이드</button><button class="quiet" data-action="home">메인으로</button></div></section>`);}

function escapeRun(){if(!run||run.phase==='ended'||flow.busy||run.pendingEscape||(run.completedRounds===0&&run.streak===0))return;run.pendingEscape=true;if(!run.doubleUsed&&Math.random()<.28){modal('악마의 마지막 제안','<b>DOUBLE OR NOTHING</b><br><br>성공하면 보상이 두 배.<br>실패하면 모두 잃습니다.<br><br><span class="risk-text">성공 확률 50%</span>',`<button class="primary" data-modal="double">계약한다</button><button class="secondary" data-modal="escape">거절하고 탈출</button>`);return;}finishRun('escape');}
function doDouble(){if(!run||!run.pendingEscape||run.phase==='ended')return;run.doubleUsed=true;if(Math.random()<.5){run.gold*=2;save.statistics.doubleWins++;addAchievement('deal');notify('계약 성공 · 보상이 두 배!');finishRun('escape');}else{run.gold=0;finishRun('ruin');}}
function renderUpgrades(){currentView='upgrades';shell(`<section class="subpage"><button class="back" data-action="home">← 돌아가기</button><p class="eyebrow">PERMANENT PACTS</p><h1>영구 업그레이드</h1><p class="subcopy">탈출 보상으로 얻은 SOUL COIN을 사용합니다.</p><div class="upgrade-list">${BALANCE.upgrades.map(u=>{const lv=save.upgrades[u.id]??0;const cost=u.cost[lv];return `<article class="upgrade-card"><div class="upgrade-icon">${icon(u.id==='insurance'?'shield':u.id==='insight'?'eye':u.id==='treasure'?'crown':'upgrade')}</div><div class="upgrade-copy"><h3>${u.name}</h3><p>${u.desc}</p><small>LEVEL ${lv} / ${u.max}</small><div class="level-track">${Array.from({length:u.max},(_,i)=>`<i class="${i<lv?'filled':''}"></i>`).join('')}</div></div><button class="buy-btn" data-action="buy" data-id="${u.id}" ${cost===undefined||save.soulCoins<cost?'disabled':''}>${cost===undefined?'MAX':`✦ ${cost}`}</button></article>`;}).join('')}</div></section>`);}
function buyUpgrade(id:string){const u=BALANCE.upgrades.find(x=>x.id===id);if(!u)return;const lv=save.upgrades[id]??0;const cost=u.cost[lv];if(cost===undefined||save.soulCoins<cost)return;save.soulCoins-=cost;save.upgrades[id]=lv+1;persist();renderUpgrades();}
function renderRecords(){currentView='records';const s=save.statistics;shell(`<section class="subpage"><button class="back" data-action="home">← 돌아가기</button><p class="eyebrow">ARCHIVE OF SOULS</p><h1>기록 보관실</h1><div class="record-grid">${[['총 RUN',s.runs],['탈출 성공',s.escapes],['RUIN',s.ruins],['최고 연승',s.bestStreak],['최고 RUN 골드',`${money(s.bestRun)} G`],['JACKPOT',s.jackpots],['누적 골드',`${money(s.lifetimeGold)} G`],['더블 성공',s.doubleWins]].map(([a,b])=>`<div><small>${a}</small><b>${b}</b></div>`).join('')}</div>${depthRecords(save)}<h2 class="section-heading">업적 <span>${save.achievements.length}/${achievements.length}</span></h2><div class="achievement-grid">${achievements.map(([id,name,desc])=>`<div class="achievement ${save.achievements.includes(id)?'unlocked':''}"><i>${save.achievements.includes(id)?'✦':'◇'}</i><b>${name}</b><small>${desc}</small></div>`).join('')}</div><h2 class="section-heading">운명 선택</h2><div class="unlocks">${CHARACTERS.map(c=>`<span>${c.icon} ${c.name}</span>`).join('')}</div></section>`);}
function renderSettings(){currentView='settings';shell(`<section class="subpage settings-page"><button class="back" data-action="home">← 돌아가기</button><p class="eyebrow">VAULT SETTINGS</p><h1>설정</h1>${settingRow('sound','효과음','간단한 보상 효과음')}${settingRow('shake','화면 흔들림','큰 보상에서 화면 흔들림')}${settingRow('reducedMotion','움직임 줄이기','애니메이션을 줄입니다')}<button class="secondary wide" data-action="tutorial-reset">튜토리얼 다시 보기</button><button class="danger-button wide" data-action="reset">저장 데이터 초기화</button></section>`);}
function settingRow(key:keyof Settings,label:string,desc:string){return `<label class="setting-row"><span><b>${label}</b><small>${desc}</small></span><input type="checkbox" data-setting="${key}" ${save.settings[key]?'checked':''}></label>`;}
function tutorialText(){return ['상자 단서를 살펴보고 하나를 고르세요.','성공하면 보상이 쌓이고 연승 배율이 올라갑니다.','RUIN을 고르면 확보한 보상을 전부 잃습니다.','현재 보상을 들고 탈출할 수도 있습니다.'][tutorialStep-1]??'욕심을 부릴지, 살아서 나갈지는 당신의 선택입니다.';}
function modal(title:string,body:string,buttons:string){document.querySelector('.modal-layer')?.remove();const div=document.createElement('div');div.className='modal-layer';div.innerHTML=`<div class="modal" role="dialog" aria-modal="true" aria-labelledby="modal-heading"><div class="modal-mark">${sigil()}</div><h2 id="modal-heading">${title}</h2><div class="modal-copy">${body}</div><div class="modal-actions">${buttons}</div></div>`;document.body.append(div);div.addEventListener('change',handleSettings);(div.querySelector('button') as HTMLButtonElement|null)?.focus();div.querySelectorAll<HTMLElement>('[data-modal]').forEach(b=>b.addEventListener('click',()=>{const action=b.dataset.modal;div.remove();if(action==='intro-go'||action==='intro-skip'){save.introSeen=true;chooseCharacter();}else if(action==='home'){if(run&&run.phase!=='ended')finishRun('ruin');renderMenu();}else if(action==='close'){if(run)run.pendingEscape=false;}else if(action==='escape')finishRun('escape');else if(action==='double')doDouble();}));div.querySelectorAll<HTMLElement>('[data-character]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.character!;div.remove();if(!save.tutorialCompleted){tutorialStep=1;save.tutorialCompleted=true;}startRun(id);}));}
function action(name:string,id?:string){if(flow.busy)return;if(flow.action(name,id))return;switch(name){case'home':if(currentView==='game'){action('menu');break;}renderMenu();break;case'start':beginIntro();break;case'upgrades':renderUpgrades();break;case'records':renderRecords();break;case'settings':if(currentView==='game'){modal('금고 설정',`${settingRow('sound','효과음','보상과 금고 잠금음')}${settingRow('shake','화면 흔들림','큰 보상에서 화면 흔들림')}${settingRow('reducedMotion','움직임 줄이기','층 이동과 빛 애니메이션 간소화')}`,`<button class="quiet" data-modal="close">계속하기</button>`);}else renderSettings();break;case'menu':modal('금고에서 나갈까요?','이번 RUN의 미확정 보상은 사라집니다.',`<button class="danger-button" data-modal="home">나가기</button><button class="quiet" data-modal="close">계속하기</button>`);break;case'continue':if(run){if(tutorialStep&&tutorialStep<4){tutorialStep++;}else tutorialStep=0;flow.continue();}break;case'escape':escapeRun();break;case'buy':buyUpgrade(id??'');break;case'tutorial-next':if(tutorialStep<4){tutorialStep++;renderGame();}else{tutorialStep=0;renderGame();}break;case'tutorial-reset':save.tutorialCompleted=false;persist();notify('다음 RUN부터 튜토리얼이 표시됩니다.');break;case'reset':modal('저장 데이터를 지울까요?','모든 기록, 업그레이드, SOUL COIN이 초기화됩니다.',`<button class="danger-button" data-modal="reset-confirm">모두 초기화</button><button class="quiet" data-modal="close">취소</button>`);document.querySelector('[data-modal="reset-confirm"]')?.addEventListener('click',()=>{save=SaveManager.reset();document.querySelector('.modal-layer')?.remove();renderMenu();});break;}}
function playTone(freq:number,duration:number){if(!save.settings.sound)return;try{const ctx=new AudioContext();const osc=ctx.createOscillator(),gain=ctx.createGain();osc.frequency.value=freq;osc.type='sine';gain.gain.setValueAtTime(.04,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+duration);osc.connect(gain).connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+duration);osc.onended=()=>void ctx.close();}catch{/* audio is optional */}}
function handleSettings(event:Event){const input=event.target as HTMLInputElement;const key=input.dataset.setting as keyof Settings|undefined;if(key){save.settings[key]=input.checked;if(key==='reducedMotion')document.documentElement.classList.toggle('reduce-motion',input.checked);persist();}}
app.addEventListener('change',handleSettings);
app.addEventListener('click',(event)=>{const el=(event.target as HTMLElement).closest('.chest');if(el&&!el.hasAttribute('data-chest'))return;});
window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!flow.busy){if(run)run.pendingEscape=false;document.querySelector('.modal-layer')?.remove();if(currentView==='game')renderGame();}});
renderMenu();
